### ISSUE TITLE
Feature Request: Ability to display a custom message after generate

### ISSUE THREAD

**Issue by kotakato** [cats-oss/scaffdog#1310]
Hello, I am using scaffdog to generate serverless functions in Go. To make the generated function work, I want to execute the following command after `generate` command.

```
cd {{ inputs.name }} && go mod tidy && chmod +x run.sh
```

It would be nice if scaffdog had the ability to run custom commands after generate, but this may not be desirable from a security standpoint. I believe that if we could instead display a message to the user asking them to execute this command, the user could easily copy, paste and execute the command.

If inputs could be used in the message, as in the example above, it would be convenient for the user to execute the command without having to modify it.

For example, I am thinking that the template document and the execution result would look something like the following. I hope you will consider this.

Template document:

```yaml
---
name: "go-function"
root: "."
output: "."
questions:
  name: "Please enter function name:"
message: |
  Please run the following commends:

    cd {{ inputs.name }} && go mod tidy && chmod +x run.sh
---
```

Execution result:

```console
$ scaffdog generate

? Please select a document. go-function
ℹ Output destination directory: "."
? Please enter function name: my-new-function

🐶 Generated 6 files!

     ✔ my-new-function/README.md
     ✔ my-new-function/Makefile
     ✔ my-new-function/cmd/main.go
     ✔ my-new-function/function.go
     ✔ my-new-function/run.sh
     ✔ my-new-function/go.mod

Please run the following commends:

  cd my-new-function && go mod tidy && chmod +x run.sh
```
